=== Reecer9714/TextAdventure/config/data.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:complexType name="BasicComponent"></xs:complexType>

<xs:element name="Equipable">
    <xs:complexType />
</xs:element>

<xs:element name="Repairable">
    <xs:complexType />
</xs:element>

<xs:element name="Breakable">
    <xs:complexType />
</xs:element>

<xs:element name="Burnable">
    <xs:complexType />
</xs:element>

<xs:element name="Durability">
    <xs:complexType>
        <xs:attribute name="value" type="xs:int" use="required" />
    </xs:complexType>
</xs:element>

<xs:simpleType name="Stat">
    <xs:restriction base="xs:int">
        <xs:minInclusive value="0" />
        <xs:maxExclusive value="20" />
    </xs:restriction>
</xs:simpleType>

<xs:element name="StatBlock">
    <xs:complexType>
        <xs:attribute name="CON" type="Stat" use="required"/>
        <xs:attribute name="STR" type="Stat" use="required"/>
        <xs:attribute name="DEX" type="Stat" use="required"/>
        <xs:attribute name="WIS" type="Stat" use="required"/>
        <xs:attribute name="INT" type="Stat" use="required"/>
        <xs:attribute name="CHA" type="Stat" use="required"/>
    </xs:complexType>
</xs:element>

<xs:element name="OnSetEffect">
    <xs:complexType>
        <xs:attribute name="trigger" type="xs:string"/>
        <xs:attribute name="triggerValue" type="xs:boolean"/>
        <xs:attribute name="targetValue" type="xs:boolean"/>
        <xs:attribute name="source" type="xs:string"/>
        <xs:attribute name="target" type="xs:string"/>
    </xs:complexType>
</xs:element>

<xs:element name="Entity">
    <xs:complexType>
        <xs:choice maxOccurs="unbounded">
            <xs:element ref="Equipable" />
            <xs:element ref="Repairable" />
            <xs:element ref="Breakable" />
            <xs:element ref="Burnable" />
            <xs:element ref="Durability" />
            <xs:element ref="StatBlock" />
            <xs:element ref="OnSetEffect" />
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
</xs:element>

<xs:element name="Entities">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="Entity" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== Reecer9714/TextAdventure/config/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<Entities 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="data.xsd">
    <Entity name="Flaming Sword">
		<Equipable />
		<Durability value="10"/>
		<Repairable />
        <Breakable />
        <Burnable />
        <OnSetEffect trigger="OnSet" 
            triggerValue="true" targetValue="true"
            source="Equipable" target="Burnable"
        />
	</Entity>
	<Entity name="Snake">
        <StatBlock 
            CON="5"
            STR="5"
            DEX="5"
            WIS="5"
            INT="5"
            CHA="5"
        />
    </Entity>
</Entities>
